"""empty message

Revision ID: 03919285c8af
Revises: caebaaf7681f
Create Date: 2021-10-14 17:38:07.266636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03919285c8af'
down_revision = 'caebaaf7681f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
