"""empty message

Revision ID: 1b7c186c7468
Revises: 8e449a507978
Create Date: 2021-10-27 17:30:25.099192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7c186c7468'
down_revision = '8e449a507978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'total_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'total_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
