"""empty message

Revision ID: 26d530e652c7
Revises: b6299b0335e3
Create Date: 2021-10-28 17:20:12.319988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d530e652c7'
down_revision = 'b6299b0335e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan', 'time',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('plan', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('plan', 'time',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
