"""empty message

Revision ID: 2c26cbf72d09
Revises: 03919285c8af
Create Date: 2021-10-15 18:20:17.622100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c26cbf72d09'
down_revision = '03919285c8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('booking', sa.Column('minutes', sa.Integer(), nullable=False))
    op.add_column('booking', sa.Column('gym_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'booking', 'gym', ['gym_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'gym_id')
    op.drop_column('booking', 'minutes')
    op.drop_table('gym')
    # ### end Alembic commands ###
