"""empty message

Revision ID: 3d697e121dd8
Revises: 29910171bb69
Create Date: 2021-10-29 17:23:21.755086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d697e121dd8'
down_revision = '29910171bb69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('award', sa.Column('image_on', sa.String(length=120), nullable=True))
    op.add_column('award', sa.Column('image_off', sa.String(length=120), nullable=True))
    op.drop_column('award', 'image_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('award', sa.Column('image_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('award', 'image_off')
    op.drop_column('award', 'image_on')
    # ### end Alembic commands ###
