"""empty message

Revision ID: a6e53999785d
Revises: a7a0da3cc751
Create Date: 2021-10-26 18:28:16.284695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e53999785d'
down_revision = 'a7a0da3cc751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_time')
    op.drop_table('time')
    op.add_column('client', sa.Column('total_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'total_time')
    op.create_table('time',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('time_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('client_exercise_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_total_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='time_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('exercise_time',
    sa.Column('time_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='exercise_time_client_id_fkey'),
    sa.ForeignKeyConstraint(['time_id'], ['time.id'], name='exercise_time_time_id_fkey'),
    sa.PrimaryKeyConstraint('time_id', 'client_id', name='exercise_time_pkey')
    )
    # ### end Alembic commands ###
