"""empty message

Revision ID: c45ae848e59b
Revises: f4f13ad8d29c
Create Date: 2021-11-02 23:12:32.013848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45ae848e59b'
down_revision = 'f4f13ad8d29c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('imagen', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'imagen')
    # ### end Alembic commands ###
