"""empty message

Revision ID: caebaaf7681f
Revises: 9d79a30af3bb
Create Date: 2021-10-14 17:36:05.466193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caebaaf7681f'
down_revision = '9d79a30af3bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('award', sa.Column('total_time', sa.Integer(), nullable=False))
    op.drop_column('award', 'totaltime')
    op.add_column('client', sa.Column('weekly_exercise', sa.Integer(), nullable=True))
    op.alter_column('client', 'gender',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('client', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('client', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('client_gender_key', 'client', type_='unique')
    op.drop_column('client', 'weeklyexercise')
    op.alter_column('stay', 'to_day',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stay', 'to_day',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('client', sa.Column('weeklyexercise', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('client_gender_key', 'client', ['gender'])
    op.alter_column('client', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('client', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('client', 'gender',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('client', 'weekly_exercise')
    op.add_column('award', sa.Column('totaltime', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('award', 'total_time')
    # ### end Alembic commands ###
